version: '3'

services:
  zig-helper:
    container_name: zig-helper
    image: abhishek1009/zig-helper:latest
    build:
      context: .  # Set the build context to the docs directory
    ports:
      - "8000:8000"
    # volume mount so that it will get the local changes automatically
    volumes:
      - ./:/home/abhishek/workspace/zig-helper  # Mounts the local docs directory to /docs in the container